---
title: "Statistical Rethinking 2 Chapter 8"
author: Vincent Arel-Bundock
output: html_document
---

```{r, message=FALSE}

library(tidyverse)
library(rstan)
library(tidybayes)
library(patchwork)
library(ghibli)
library(bayesplot)
options(mc.cores = parallel::detectCores())
theme_custom <- theme_minimal()
theme_set(theme_classic())
knitr::opts_chunk$set(message=FALSE, warning=FALSE)

```

# Section 9.4

```{r, message=FALSE}

# load and standardize data
rugged <- read.csv('../rethinking/data/rugged.csv', sep = ';') %>%
          mutate(log_gdp = log(rgdppc_2000),
                 log_gdp_std = log_gdp / mean(log_gdp, na.rm = TRUE),
                 rugged_std = rugged / max(rugged, na.rm = TRUE),
                 region = ifelse(cont_africa == 1, 'Africa', 'Not Africa')) %>%
          select(country, log_gdp_std, rugged_std, region) %>%
          drop_na
dat <- compose_data(rugged)

# Stan model
model <- '
data {
  int<lower=1> n;        // number of observations
  vector[n] log_gdp_std; // outcome
  vector[n] rugged_std;  // regressor
  int region[n];            // africa indicator
}
parameters {
  real<lower=0> sigma;
  vector[2] a;
  vector[2] b;
}
transformed parameters{
  vector[n] mu;
  for (i in 1:n) {
    mu[i] = a[region[i]] + b[region[i]] * (rugged_std[i] - 0.215);
  }
}
model {
  a ~ normal(1, 0.1);
  b ~ normal(0, 0.3);
  sigma ~ exponential(1);
  log_gdp_std ~ normal(mu, sigma);
}
'

mod <- stan(model_code = model, data = dat, control = list(adapt_delta = 0.99), iter = 10000)

summary(mod, c('a', 'b'))$summary

```

# Section 9.5

```{r, fig.asp = .3}

set.seed(11)
dat <- data.frame(y = c(-1, 1)) %>%
       compose_data

model <- '
data {
  int<lower=1> n;
  real y[n];
}
parameters {
  real alpha;
  real<lower=0> sigma;
}
transformed parameters {
  real mu;
  mu = alpha;
}
model {
  y ~ normal(mu, sigma);
  alpha ~ normal(0, 1000);
  sigma ~ exponential(0.0001);
}
'

mod <- stan(model_code = model, data = dat, control = list(adapt_delta = 0.99), iter = 1000)

summary(mod, c('alpha', 'sigma'))$summary

mcmc_trace(mod, c('alpha', 'sigma'))

```

More information in priors:

```{r, fig.asp = .3}

model <- '
data {
  int<lower=1> n;
  real y[n];
}
parameters {
  real alpha;
  real<lower=0> sigma;
}
transformed parameters {
  real mu;
  mu = alpha;
}
model {
  y ~ normal(mu, sigma);
  alpha ~ normal(0, 10);
  sigma ~ exponential(1);
}
'

mod <- stan(model_code = model, data = dat, control = list(adapt_delta = 0.99), iter = 10000)

summary(mod, c('mu', 'sigma'))$summary

mcmc_trace(mod, c('alpha', 'sigma'))

```

## Section 9.5.4

Unidentifiable:

```{r, fig.asp = .3}

set.seed(41)
dat <- data.frame(y = rnorm(100)) %>%
       compose_data

model <- '
data {
  int<lower=1> n;
  real y[n];
}
parameters {
  real alpha[2];
  real<lower=0> sigma;
}
transformed parameters {
  real mu;
  mu = alpha[1] + alpha[2];
}
model {
  y ~ normal(mu, sigma);
  alpha[1] ~ normal(0, 1000);
  alpha[2] ~ normal(0, 1000);
  sigma ~ exponential(1);
}
'

mod <- stan(model_code = model, data = dat, control = list(adapt_delta = 0.99), iter = 10000)

summary(mod, c('alpha', 'sigma'))$summary

mcmc_trace(mod, c('alpha[1]', 'alpha[2]', 'sigma'))

```

Weakly regularized priors:

```{r, fig.asp = .3}

model <- '
data {
  int<lower=1> n;
  real y[n];
}
parameters {
  real alpha[2];
  real<lower=0> sigma;
}
transformed parameters {
  real mu;
  mu = alpha[1] + alpha[2];
}
model {
  y ~ normal(mu, sigma);
  alpha[1] ~ normal(0, 10);
  alpha[2] ~ normal(0, 10);
  sigma ~ exponential(1);
}
'

mod <- stan(model_code = model, data = dat, control = list(adapt_delta = 0.99), iter = 10000)

summary(mod, c('alpha', 'sigma'))$summary

mcmc_trace(mod, c('alpha[1]', 'alpha[2]', 'sigma'))

```
