---
title: "Statistical Rethinking 2: Chapter 12"
author: Vincent Arel-Bundock
output: html_document
---

# Status

Estimated and checked against the book:

* m12.2
* m12.3
* m12.4
* m12.5
* m12.6

Different results:

* m12.1

# Libraries

```{r, include=FALSE}
# set default graphics theme if Vincent's personal package is installed
if (requireNamespace('vincent', quietly = TRUE)) {
        vincent::theming()
}
```

```{r, results=FALSE, message=FALSE}
library(tidyverse)
library(tidybayes)
library(rstan)
library(patchwork)
library(rethinking)
options(mc.cores = 4)
```

# Section 12.1: Over-dispersed counts

*Warning*: I have not yet been able to replicate the `ulam` results for `m12.1` in `rstan`.

```{r, warning=FALSE, message=FALSE, results=FALSE}
stan_program <- '
data {
    int n;
    int applications[n];
    int admit[n];
    int gender[n];
}
parameters {
    vector[2] a;
    real<lower=0> phi;
}
transformed parameters {
    real theta;
    theta = phi + 2;
}
model {
    vector[n] pbar;
    phi ~ exponential(1);
    a ~ normal(0, 1.5);
    for (i in 1:n) {
        pbar[i] = a[gender[i]];
        pbar[i] = inv_logit(pbar[i]);
    }
    admit ~ beta_binomial(applications, pbar * theta, (1 - pbar) * theta);
}
generated quantities {
    real da;
    da = a[1] - a[2];
}
'

stan_data <- read.csv('data/UCBadmit.csv', sep = ';') %>%
             rename(gender = applicant.gender) %>%
             mutate(gender = ifelse(gender == 'female', 2, 1)) %>%
             compose_data

m12.1 <- stan(model_code = stan_program, data = stan_data, iter = 5000, 
              control = list(adapt_delta = .95))
```

```{r}
summary(m12.1, c('a', 'phi'))$summary
```

```{r, warning=FALSE, message=FALSE, results=FALSE}
stan_data <- read.csv('data/Kline.csv', sep = ';') %>%
             mutate(logpop = standardize(log(population))) %>%
             compose_data(n_contact = n_distinct(contact))

stan_program <- "
data{
    int total_tools[10];
    int population[10];
    int contact[10];
}
parameters{
    vector[2] a;
    vector<lower=0>[2] b;
    real<lower=0> g;
    real<lower=0> phi;
}
model{
    vector[10] lambda;
    phi ~ exponential( 1 );
    g ~ exponential( 1 );
    b ~ exponential( 1 );
    a ~ normal( 1 , 1 );
    for ( i in 1:10 ) {
        lambda[i] = exp(a[contact[i]]) * population[i]^b[contact[i]]/g;
    }
    total_tools ~ neg_binomial_2( lambda , phi );
}
"
m12.2 <- stan(model_code = stan_program, data = stan_data)
```

```{r}
summary(m12.2, c('a', 'b', 'phi', 'g'))$summary
```

# Section 12.2: Zero-inflated outcomes

```{r}
set.seed(365)
prob_drink <- .2
rate_work <- 1
n <- 365
drink <- rbinom(n, 1, prob_drink)
y <- (1 - drink) * rpois(n, rate_work)

stan_data <- list(y = y, n = length(y))

stan_program <- "
data {
    int n;
    int y[n];
}
parameters {
    real ap;
    real al;
}
model {
    real p;
    real lambda;
    p = inv_logit(ap);
    lambda = exp(al);
    ap ~ normal(-1.5, 1);
    al ~ normal(1, .5);
    for ( i in 1:n ) {
        if (y[i] == 0)
            target += log_mix( p , 0 , poisson_lpmf(0 | lambda) );
        if (y[i] > 0)
            target += log1m( p ) + poisson_lpmf(y[i] | lambda );
    }
}
"
m12.3 <- stan(model_code = stan_program, data = stan_data)
```

```{r}
summary(m12.3, c('al', 'ap'))$summary
```

# Section 12.3: Ordered categorical outcomes

```{r, warning=FALSE, message=FALSE, results=FALSE}
stan_data <- read.csv('data/Trolley.csv', sep = ';') %>%
             compose_data(k = n_distinct(response) - 1)

stan_program <- "
data {
    int n;
    int k;
    int response[n];
}
parameters {
    ordered[k] cutpoints;
}
model {
    for (i in 1:n) {
        response[i] ~ ordered_logistic(0, cutpoints);
    }
    cutpoints ~ normal(0, 15);
}
"
m12.4 <- stan(model_code = stan_program, data = stan_data)
```

```{r, warning=FALSE, message=FALSE, results=FALSE}
stan_data <- read.csv('data/Trolley.csv', sep = ';') %>%
             compose_data(k = n_distinct(response) - 1)

stan_program <- "
data {
    int n;
    int k;
    int response[n];
    int action[n];
    int intention[n];
    int contact[n];
}
parameters {
    ordered[k] cutpoints;
    real bA;
    real bI;
    real bC;
    real bIA;
    real bIC;
}
model {
    vector[n] BI;
    vector[n] phi;
    for (i in 1:n) {
        BI[i] = bI + bIA * action[i] + bIC * contact[i];
        phi[i] = bA * action[i] + bC * contact[i] + BI[i] * intention[i];
        response[i] ~ ordered_logistic(phi[i], cutpoints);
    }
    cutpoints ~ normal(0, 15);
    bA ~ normal(0, .5);
    bI ~ normal(0, .5);
    bC ~ normal(0, .5);
    bIA ~ normal(0, .5);
    bIC ~ normal(0, .5);
}
"
m12.5 <- stan(model_code = stan_program, data = stan_data)
```

```{r}
datplot <- m12.5 %>%
           gather_draws(bA, bI, bC, bIA, bIC) %>%
           mean_qi()

ggplot(datplot, aes(y = .variable, x = .value, xmin = .lower, xmax = .upper)) +
    geom_pointrange() +
    geom_vline(xintercept = 0, linetype = 'dotted')
```

# Section 12.4: Ordered categorical predictors

```{r, warning=FALSE, message=FALSE, results=FALSE}
stan_program <- '
data{
    int n;
    int response[n];
    int contact[n];
    int intention[n];
    int action[n];
    int edu_new[n];
    vector[7] alpha;
}
parameters{
    ordered[6] kappa;
    real bE;
    real bC;
    real bI;
    real bA;
    simplex[7] delta;
}
model{
    vector[n] phi;
    vector[8] delta_j;
    delta ~ dirichlet( alpha );
    delta_j = append_row(0, delta);
    bA ~ normal( 0 , 1 );
    bI ~ normal( 0 , 1 );
    bC ~ normal( 0 , 1 );
    bE ~ normal( 0 , 1 );
    kappa ~ normal( 0 , 1.5 );
    for ( i in 1:n ) {
        phi[i] = bE * sum(delta_j[1:edu_new[i]]) + 
                 bA * action[i] + 
                 bI * intention[i] + 
                 bC * contact[i];
    }
    for ( i in 1:n ) response[i] ~ ordered_logistic( phi[i] , kappa );
}
'

stan_data <- read.csv('data/Trolley.csv', sep = ';') %>%
             # ordered education levels
             mutate(edu_new = factor(edu, levels = c("Elementary School",
                                                     "Middle School",
                                                     "Some High School",
                                                     "High School Graduate",
                                                     "Some College",
                                                     "Bachelor's Degree",
                                                     "Master's Degree",
                                                     "Graduate Degree"))) %>%
            compose_data(alpha = rep(2, 7))

m12.6 <- stan(model_code = stan_program, data = stan_data)
```

```{r}
summary(m12.6, c('bE', 'bC', 'bI', 'bA', 'delta'))$summary
```
