---
title: "Statistical Rethinking 2: Chapter 16"
author: Vincent Arel-Bundock
output: html_document
---

# Status

Estimated and checked against book:

* m16.1
* m16.4

Stan code printed in the book or in the `rethinking` package:

* m16.2
* m16.5

This model is not discussed in my copy of the book:

* m16.3

# Libraries

```{r, include=FALSE}
# set default graphics theme if Vincent's personal package is installed
if (requireNamespace('vincent', quietly = TRUE)) {
        vincent::theming()
}
```

```{r, results=FALSE, message=FALSE}
library(tidyverse)
library(tidybayes)
library(rstan)
library(patchwork)
library(rethinking)
options(mc.cores = 4)
```

# Section 16.1: Geometric people

```{r, warning=FALSE, message=FALSE, results=FALSE}
stan_data <- read.csv('data/Howell1.csv', sep = ';') %>%
             mutate(weight = weight / mean(weight),
                    height = height / mean(height)) %>%
             compose_data

stan_program <- "
data {
    int n;
    vector[n] weight;
    vector[n] height;
}
parameters {
    real p;
    real<lower=0> k;
    real<lower=0> sigma;
}
model {
    vector[n] mu;
    for (i in 1:n) {
        mu[i] = log(3.141593 * k * p^2 * height[i]^3);
    }
    weight ~ lognormal(mu, sigma);
    p ~ beta(2, 18);
    k ~ exponential(.5);
    sigma ~ exponential(1);
}
"
m16.1 <- stan(model_code = stan_program, data = stan_data)
```

```{r}
m16.1
```

# Section 16.3: Ordinary differential nut cracking

```{r, warning=FALSE, message=FALSE, results=FALSE}

stan_data <- read.csv('data/Panda_nuts.csv', sep = ';') %>%
             mutate(age = age / max(age)) %>%
             compose_data

stan_program <- "
data {
    int n;
    int nuts_opened[n];
    vector[n] age; 
    vector[n] seconds; 
}
parameters {
    real phi;
    real k;
    real theta;
}
model {
    vector[n] lambda;
    for (i in 1:n) {
        lambda[i] = seconds[i] * phi * (1 - exp(-k * age[i]))^theta;
    }
    nuts_opened ~ poisson(lambda);
    phi ~ lognormal(log(1), .1);
    k ~ lognormal(log(2), .25);
    theta ~ lognormal(log(5), .25);
}
"
m16.4 <- stan(model_code = stan_program, data = stan_data)
```

```{r}
m16.4
```
